name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://g114056175:${HF_TOKEN}@huggingface.co" > ~/.git-credentials
          git remote add hf https://huggingface.co/spaces/g114056175/DRL-hw1-demo || true
          git push hf main --force
